image: elixir:1.6.5

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

build:
  variables:
    MIX_ENV: test
  script:
    - mix compile --warnings-as-errors --force
    - mix format --check-formatted --dry-run
    - mix coveralls.html
    - mix test
  coverage: '/\[TOTAL\]\s+(\d+\.\d+)%/'
  artifacts:
    paths:
      - cover/

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mv cover/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
